INFO - 2023-06-14 08:45:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 08:45:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'codeigniter', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('knkn', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'knkn', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(31): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('knkn', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'knkn', Array, Array)
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(31): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-06-14 08:45:57 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('knkn', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'knkn', [...], [...])
 6 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Auth.php(31): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 08:47:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 09:55:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 09:55:30 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 09:55:30 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:02:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:02:20 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:02:20 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:02:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:02:26 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:02:26 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:04:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:04:59 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:04:59 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:06:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:06:22 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:06:22 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
CRITICAL - 2023-06-14 10:06:39 --> syntax error, unexpected token ")"
in APPPATH\Controllers\Auth.php on line 33.
 1 SYSTEMPATH\Router\Router.php(507): CodeIgniter\Router\AutoRouter->getRoute('Auth')
 2 SYSTEMPATH\Router\Router.php(206): CodeIgniter\Router\Router->autoRoute('Auth')
 3 SYSTEMPATH\CodeIgniter.php(815): CodeIgniter\Router\Router->handle('Auth')
 4 SYSTEMPATH\CodeIgniter.php(449): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:07:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:07:23 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:07:23 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:08:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:08:54 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:08:54 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:08:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:08:59 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:08:59 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:09:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:09:05 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:09:05 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:10:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:10:08 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:10:08 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:11:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:11:14 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:11:14 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:16:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:16:57 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:16:57 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:21:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:21:10 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:21:10 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:21:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:21:16 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:21:16 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:21:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:21:20 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(32): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:21:20 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(32): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:31:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:31:46 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:31:46 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:32:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:32:28 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:32:28 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:33:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:33:16 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('dfsdfsfdfs', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'dfsdfsfdfs', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:33:16 --> Table 'codeigniter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'dfsdfsfdfs\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'dfsdfsfdfs\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'dfsdfsfdfs\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('dfsdfsfdfs', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'dfsdfsfdfs', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
ERROR - 2023-06-14 10:49:05 --> mysqli_sql_exception: Table 'tbl_users' already exists in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('CREATE TABLE `t...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `t...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `t...')
#4 C:\xampp\htdocs\codeigniter\framework-master\app\Database\Migrations\2023-06-14-104825_Home.php(68): CodeIgniter\Database\Forge->createTable('tbl_users')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(877): App\Database\Migrations\Home->up()
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codeigniter\framework-master\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-06-14 10:49:47 --> mysqli_sql_exception: Table 'tbl_users' already exists in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('CREATE TABLE `t...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `t...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `t...')
#4 C:\xampp\htdocs\codeigniter\framework-master\app\Database\Migrations\2023-06-14-104825_Home.php(68): CodeIgniter\Database\Forge->createTable('tbl_users')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(877): App\Database\Migrations\Home->up()
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codeigniter\framework-master\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
INFO - 2023-06-14 10:50:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:50:52 --> mysqli_sql_exception: Table 'home.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:50:52 --> Table 'home.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 10:55:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 10:55:36 --> mysqli_sql_exception: Table 'home.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('dfsdfsfdfs', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'dfsdfsfdfs', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 10:55:36 --> Table 'home.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'dfsdfsfdfs\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'dfsdfsfdfs\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'dfsdfsfdfs\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('dfsdfsfdfs', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'dfsdfsfdfs', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 11:00:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 11:00:54 --> mysqli_sql_exception: Table 'home.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 11:00:54 --> Table 'home.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 11:05:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 11:05:13 --> mysqli_sql_exception: Table 'home.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 11:05:13 --> Table 'home.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'anne-marie\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('anne-marie', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'anne-marie', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 11:09:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 11:10:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 11:12:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 11:12:13 --> mysqli_sql_exception: Table 'home.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 11:12:13 --> Table 'home.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 11:12:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 11:12:47 --> mysqli_sql_exception: Table 'home.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 11:12:47 --> Table 'home.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 11:13:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 11:13:10 --> mysqli_sql_exception: Table 'home.users' doesn't exist in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', Array, Array)
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(33): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-06-14 11:13:10 --> Table 'home.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'LiLi\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(321): CodeIgniter\Validation\StrictRules\Rules->is_unique('LiLi', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(179): CodeIgniter\Validation\Validation->processRules('username', 'username', 'LiLi', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(33): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 11:20:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 11:27:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 11:27:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 11:27:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 19:36:52 --> mysqli_sql_exception: Table 'tbl_users' already exists in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('CREATE TABLE `t...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `t...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `t...')
#4 C:\xampp\htdocs\codeigniter\framework-master\app\Database\Migrations\2023-06-14-104825_Home.php(68): CodeIgniter\Database\Forge->createTable('tbl_users')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(877): App\Database\Migrations\Home->up()
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codeigniter\framework-master\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-06-14 19:38:41 --> mysqli_sql_exception: Table 'tbl_users' already exists in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('CREATE TABLE `t...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `t...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `t...')
#4 C:\xampp\htdocs\codeigniter\framework-master\app\Database\Migrations\2023-06-14-104825_Home.php(68): CodeIgniter\Database\Forge->createTable('tbl_users')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(877): App\Database\Migrations\Home->up()
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codeigniter\framework-master\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-06-14 19:42:22 --> mysqli_sql_exception: Table 'tbl_users' already exists in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('CREATE TABLE `t...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `t...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `t...')
#4 C:\xampp\htdocs\codeigniter\framework-master\app\Database\Migrations\2023-06-14-104825_Home.php(68): CodeIgniter\Database\Forge->createTable('tbl_users')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(877): App\Database\Migrations\Home->up()
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codeigniter\framework-master\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-06-14 19:44:15 --> mysqli_sql_exception: Table 'tbl_users' already exists in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('CREATE TABLE `t...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `t...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `t...')
#4 C:\xampp\htdocs\codeigniter\framework-master\app\Database\Migrations\2023-06-14-104825_Home.php(68): CodeIgniter\Database\Forge->createTable('tbl_users')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(877): App\Database\Migrations\Home->up()
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codeigniter\framework-master\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-06-14 19:51:40 --> mysqli_sql_exception: Table 'tbl_users' already exists in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('CREATE TABLE `t...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `t...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `t...')
#4 C:\xampp\htdocs\codeigniter\framework-master\app\Database\Migrations\2023-06-14-104825_Home.php(68): CodeIgniter\Database\Forge->createTable('tbl_users')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(877): App\Database\Migrations\Home->up()
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codeigniter\framework-master\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
INFO - 2023-06-14 21:15:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2023-06-14 21:15:51 --> Call to undefined function App\Controllers\random_string()
in APPPATH\Controllers\Auth.php on line 49.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 21:31:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 21:32:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2023-06-14 21:32:41 --> Undefined array key "is_active"
in APPPATH\Controllers\Log.php on line 38.
 1 APPPATH\Controllers\Log.php(38): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "is_active"', 'C:\\xampp\\htdocs\\codeigniter\\framework-master\\app\\Controllers\\Log.php', 38)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Log->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Log))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 21:53:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 21:56:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 21:56:23 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(59): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-06-14 21:56:23 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (3, \'843d44cd0db4c85385\', \'2023-06-14 21:56:23\', \'2023-06-14 21:56:23\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (3, \'843d44cd0db4c85385\', \'2023-06-14 21:56:23\', \'2023-06-14 21:56:23\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (3, \'843d44cd0db4c85385\', \'2023-06-14 21:56:23\', \'2023-06-14 21:56:23\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (:id:, :activation_code:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(59): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 22:03:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 22:03:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 22:25:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 22:26:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 22:31:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 22:38:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 22:39:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 22:39:58 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(59): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-06-14 22:39:58 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (4, \'e299e899f6c5fb19e9\', \'2023-06-14 22:39:58\', \'2023-06-14 22:39:58\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (4, \'e299e899f6c5fb19e9\', \'2023-06-14 22:39:58\', \'2023-06-14 22:39:58\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (4, \'e299e899f6c5fb19e9\', \'2023-06-14 22:39:58\', \'2023-06-14 22:39:58\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (:id:, :activation_code:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(59): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
INFO - 2023-06-14 22:40:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-14 22:41:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-14 22:41:36 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\codeigniter\framework-master\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter\framework-master\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter\framework-master\app\Controllers\Auth.php(59): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\codeigniter\framework-master\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter\framework-master\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-06-14 22:41:36 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (5, \'de266f6e4dd53991ba\', \'2023-06-14 22:41:36\', \'2023-06-14 22:41:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (5, \'de266f6e4dd53991ba\', \'2023-06-14 22:41:36\', \'2023-06-14 22:41:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (5, \'de266f6e4dd53991ba\', \'2023-06-14 22:41:36\', \'2023-06-14 22:41:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_activation` (`id`, `activation_code`, `created_at`, `updated_at`) VALUES (:id:, :activation_code:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(59): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codeigniter\\framework-master\\public\\index.php')
ERROR - 2023-06-14 22:44:54 --> mysqli_sql_exception: Table 'tbl_users' already exists in C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MySQLi\Connection.php(295): mysqli->query('CREATE TABLE `t...', 0)
#1 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\codeigniter\framework-master\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `t...')
#3 C:\xampp\htdocs\codeigniter\framework-master\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `t...')
#4 C:\xampp\htdocs\codeigniter\framework-master\app\Database\Migrations\2023-06-14-224352_Newest.php(72): CodeIgniter\Database\Forge->createTable('tbl_users')
#5 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(877): App\Database\Migrations\Home->up()
#6 C:\xampp\htdocs\codeigniter\framework-master\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codeigniter\framework-master\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codeigniter\framework-master\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codeigniter\framework-master\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
